name: Build
on: [push]
  
jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Activate
      - name: Activate Unity
        uses: webbertakken/unity-activate@v1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2019.3.7f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2019.3.7f1
          targetPlatform: WebGL
      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build