name: Build
on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Activate
      - name: Activate Unity
        uses: webbertakken/unity-activate@v1.2
        with:
          unityVersion: 2019.3.7f1
          targetPlatform: WebGL

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.0
        with:
          unityVersion: 2019.3.7f1
          targetPlatform: WebGL
          
      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

      # GitHub Pages
      - name: deploy docs
        uses: appleboy/gh-pages-action@v0.0.2
        with:
          username: ${{ secrets.PAGES_USERNAME }}
          password: ${{ secrets.PAGES_PASSWORD }}
          remote_url: https://github.com/pruijs/TravisTestPages.git